bump_version: null
lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
  multiqc_config: false
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: Athanasios Baltzis, Jose Espinosa-Carrasco, Harshil Patel
  description: Protein 3D structure prediction pipeline
  force: false
  is_nfcore: true
  name: proteinfold
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.1.1
update: null
